# Generated by Django 2.2 on 2019-08-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='学校名称'),
        ),
    ]
