# Generated by Django 2.2 on 2019-08-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190823_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=100, verbose_name='积分'),
        ),
    ]
